print syntax
  File "./hc-harvester", line 38
    print 'Running ' + cmd
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Running ' + cmd)